#!/bin/bash

for i in $@; do
	if [ -e */${i##*/}/spec ]; then
		unset VER REL
		source */${i##*/}/spec
		printf -- "- [ ] \`${i##*/}\` v$VER-$REL\n"
	else
		echo "Warning: package ${i##*/} is not found in the source tree."
	fi
done | \
	sed -e 's/-$//' | sort
