#!/bin/bash

_help_message() {
	printf "\
Useage:
	bump-rel PACKAGE_GROUPS [-c MESSAGE]
	
	- PACKAGE_GROUPS: Path to the list of packages.
	- -c: will commit REL bump if present
"
}

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
	_help_message
	exit 0
fi

if [ -z "$1" ]; then
	printf "[!!!] Please specify a package group.\n"
	_help_message
	exit 1
fi

if [ -z "$2" ]; then
	printf "[!!!] Please specify a package group.\n"
	_help_message
	exit 1
fi

# Main stuff
for i in $(cat $1); do
	if ! [[ -e $i ]]; then
		echo [!!!] Package $i does not exists!
		continue
	fi
	
	OLD_REL=$(grep "^REL" $i/spec | cut -d "=" -f2)

	if ! [[ "$OLD_REL" =~ ^[0-9]+$ ]]; then
		OLD_REL=0
		REL=1
		sed -i "/^VER/a REL=1" $i/spec
	else
		REL=$((OLD_REL+1))
		sed -i "/REL/ s/$OLD_REL/$REL/" $i/spec
	fi
	
	printf "[iii] update $i's REL from $OLD_REL to $REL.\n"

	# If you want to commit it.
	if [[ "$2" == "-c" ]]; then
		git add $i/spec
		git commit -m "${i##*/}: bump REL due to $3"
	fi
done
