#!/bin/sh
# Super crude and simple for now, just to show the basic ideas of
# how I actually built RPM builds of AOSC OS - and from what I can
# see so far, this method works just fine.
#
# Jeff Bai

# Get needed tools for RPM conversion
apt update &&
apt install zypper --yes &&

# Remove PackageKit as it is not supported on RPM for now
apt purge packagekit gnome-packagekit apper muon-explorer --yes &&

# Get the list of DPKG packages with "Installed" state, specifically:
# Includes Zypper at this point, of course...
dpkg -l | grep ^i | cut -d\  -f 2 > /run/aosc-dpkg-list

# Configure Zypper repositories
zypper ar http://repo.anthonos.org/os3-next/os3-rpm "AOSC OS3"

# Install RPM packages
zypper refresh &&
zypper install $(cat /run/aosc-dpkg-list)

# Now purge DPKG and Apt from the system
apt purge apt dpkg --force-yes && # Does this skip "Yes, do as I say!"?

# And clean up...
rm -rf /var/cache/apt
rm -rf /var/lib/{dpkg,apt,PackageKit}

# Boom, and done
echo "Conversion complete!"
