#!/bin/bash
if [ -z "$1" ]; then
   echo "[!!!] Please specify a LDAP user!"
   exit 1
fi

if [ -z "$2" ]; then
   echo "[!!!] Please specify a branch!"
   exit 1
fi

rsync --ignore-existing -rlOvhze ssh --progress debs/* $1@repo.aosc.io:/mirror/debs/pool/"$2"/main
