#!/bin/bash

rm -rf /tmp/packages.json
wget 'https://packages.aosc.io/srcupd/aosc-os-abbs?type=json&page=all' \
    -O /tmp/packages.json

update-pkgs.py -j /tmp/packages.json -s /tmp/cache.txt -q

for i in "$@"; do
    update-pkgs.py -l /tmp/cache.txt -c $i -r -q
done

rm -rf /tmp/cache.txt
