#!/bin/bash

rm -rf /tmp/repology.json
update-pkgs.py -d /tmp/repology.json
update-pkgs.py -j /tmp/repology.json -s /tmp/cache.txt -q

for i in "$@"; do
    update-pkgs.py -l /tmp/cache.txt -c $i -r -q
done

rm -rf /tmp/cache.txt
