#!/usr/bin/python3

import sys
import requests
import os


def get_rebuilds_list(package_name: str) -> list:
    response = requests.get(
        "https://packages.aosc.io/revdep/{}?type=json".format(package_name))
    if response.status_code != 200:
        print("Request packages.aosc.io failed!")
        exit(1)
    package_info = response.json()
    not_sorted_rebuilds_list = []
    for group in package_info["sobreaks"]:
        for package in group:
            not_sorted_rebuilds_list.append(package)
    if package_info["sobreaks_circular"] != None:
        not_sorted_rebuilds_list += package_info["sobreaks_circular"]
    rebuilds_list = []
    rebuilds_list = [
        i for i in not_sorted_rebuilds_list if i not in rebuilds_list]
    if len(rebuilds_list) == 0:
        print("Package {} has nothing to rebuild!".format(package_name))
        exit(0)
    return rebuilds_list


def gen_rebuilds_list_string(rebuilds_list: list) -> str:
    rebuilds_path_list = [search_package_path(i) for i in rebuilds_list]
    rebuilds_path_list = [
        i for i in rebuilds_path_list if i != None and len(i.split('/')) == 2]
    return "\n".join(rebuilds_path_list) + "\n"


def search_package_path(package_name: str) -> str:
    for root, dirs, _ in os.walk(".", topdown=False):
        for name in dirs:
            if name == package_name:
                return os.path.join(root, name)[2:]


def write_strig_to_file(package_name: str, rebuilds_path_list_str: str) -> None:
    with open('groups/{}-rebuilds'.format(package_name), "w") as f:
        f.write(rebuilds_path_list_str)
        print('groups/{}-rebuils created!'.format(package_name))


def main():
    if len(sys.argv) != 2:
        print("Usage: make-rebuilds-list PACKAGE_NAME")
        exit(1)
    package_name = sys.argv[1]
    request_list = get_rebuilds_list(package_name)
    rebuilds_path_list_str = gen_rebuilds_list_string(request_list)
    write_strig_to_file(package_name, rebuilds_path_list_str)


if __name__ == '__main__':
    main()
